### ISSUE TITLE
Mejorar el diseño del correo

### ISSUE THREAD

**Issue by sami-sopas** [sami-sopas/PetApp#11]
Hacerlo bonito, esteril, lo que quieran, ya sea con html, css hardcodeado, tailwind, lo que sea, pero que se vea bonito, el archivo a modificar es un html dentro en la siguiente direccion: views -> email -> thank-you
![image](https://github.com/sami-sopas/PetApp/assets/99571985/2783ba98-ff94-47c2-8607-cfc5eaad0898)

**Comment by B4s4cch1** [comment]
Hay que arreglar que se vean las imágenes
![image](https://github.com/sami-sopas/PetApp/assets/110313381/80408cec-e6e4-43cc-8d49-dcb6dff8dd72)
