### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by cybness** [sami-sopas/PetApp#3]
- [ ] Detalles en admin
- [ ] Cambio de data en blog
- [ ] Cambiar el lore ipsul
- [ ] Restringir el acceso a rutas si no se tiene sesión iniciada (Contactar a dueño de mascota, subir mascota nueva)
- [ ] Enlacces de index
- [ ] Contact us (view and send data)

**Comment by sami-sopas** [comment]
admin ya quedo
el blog creo que no dara tiempo de hacerlo
un falta el lorem pero eso juanito
ya se restringieron las rutas
ya se acomodaron lo de los enlaces
lo de contact us no lo veo necesario (mejor arreglamos la pagina principal)
