### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by B4s4cch1** [sami-sopas/PetApp#8]
Que se vea bonito el register.
![image](https://github.com/sami-sopas/PetApp/assets/110313381/9a5d05ba-9e5c-4c0c-ac60-dfc5f057100a)

**Comment by B4s4cch1** [comment]
https://codepen.io/andytran/pen/GpyKLM
Ponerle eso para que se vea más bonito

**Comment by sami-sopas** [comment]
esta culei, ese mejor modificamos el actual para q no se vea tan descarao
